//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPlat_Auto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string idNumber { get; set; }
        public string Bank { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
