//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesPlat_Auto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int salesId { get; set; }
        public int SalesManId { get; set; }
        public int CustomerId { get; set; }
        public int StockId { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesMan SalesMan { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
